- name: Restart server
  command: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
  async: 1
  poll: 0
  ignore_errors: true
  become: true

- name: Wait for server to restart
  local_action:
    module: wait_for
      host="{{ inventory_hostname }}"
      port=22
      delay=10
    become: false
 
- name: Restart k3s
  ansible.builtin.service:
    name: k3s
    state: restarted
  when: ansible_facts.services['k3s.service']
