apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: wildcard.home
  namespace: certificates
spec:
  secretName: wildcard.home
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kube-system, argocd"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kube-system, argocd"
  duration: 8760h # Year
  renewBefore: 720h # 30 days
  isCA: false
  subject:
    organizations:
    - "home"
  privateKey:
    algorithm: ECDSA
    size: 384
    encoding: PKCS8
    rotationPolicy: Always
  dnsNames:
  - "*.home"
  - "home"
  issuerRef:
    name: cluster-issuer-selfsigned
    kind: ClusterIssuer
    group: cert-manager.io