- name: Set a hostname
  ansible.builtin.hostname:
    name: {{ inventory_hostname }}
    use: debian
  notify: 
    - Restart server
    - Wait for server to restart

- name: k3s config directories
  become: true
  ansible.builtin.file:
   path: '{{ item.path }}'
   state: directory
  loop:
   - { path: /etc/rancher/k3s.config.d }
   - { path: /etc/rancher/k3s }

- name: copy kubelet.config
  become: true
  ansible.builtin.copy:
   src: files/kubelet.config
   dest: /etc/rancher/k3s.config.d