- name: Set a hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: debian
  notify: 
    - Restart server
    - Wait for server to restart

- name: k3s config directories
  become: true
  ansible.builtin.file:
   path: "{{ item.path }}"
   state: directory
  loop:
   - { path: /etc/rancher/k3s.config.d }
   - { path: /etc/rancher/k3s }

- name: copy kubelet.config
  become: true
  ansible.builtin.copy:
   src: files/kubelet.config
   dest: /etc/rancher/k3s.config.d

- name: Soft link to kubelet config
  become: true
  ansible.builtin.file:
   src: /etc/rancher/k3s.config.d/kubelet.config
   dest: /etc/rancher/k3s/kubelet.config
   state: link

- name: Install python
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg: 
      - python3
      - python3-pip
      - awscli

- name: Install python modules
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: "1"
  ansible.builtin.pip:
    name:
      - boto3
      - botocore
      - kubernetes