- name: Get token
  environment:
    AWS_ACCESS_KEY_ID: "{{ ANSIBLE_AWS_ACCESS_KEY }}"
    AWS_SECRET_ACCESS_KEY: "{{ ANSIBLE_AWS_SECRET_KEY }}"
    AWS_DEFAULT_REGION: "eu-central-1"
  set_fact:
    token: "{{ lookup('amazon.aws.aws_ssm', '/self_hosted/k3s_token') }}"

- name: Mount up device
  when: mount is defined
  ansible.posix.mount:
    path: {{ item.path }}
    src: {{ item.hw_label }}
    fstype: {{ item.fstype }}
    state: {{ item.state }}
  loop: "{{ mount }}"

- name: Create k3s config.yaml
  become: true
  ansible.builtin.template:
   src: templates/config.yaml.j2
   dest: /etc/rancher/k3s.config.d/config.yaml

- name: Soft link to k3s config
  become: true
  ansible.builtin.file:
   src: /etc/rancher/k3s.config.d/config.yaml
   dest: /etc/rancher/k3s/config.yaml
   state: link

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Install k3s agent
  become: true
  run_once: true
  ansible.builtin.shell:
    cmd: wget -qO - https://get.k3s.io | INSTALL_K3S_VERSION="{{ k3s_version }}" sh -s - agent
  when: "'k3s-agent.service' not in ansible_facts.services"

- name: Label node
  ansible.builtin.shell: kubectl label nodes {{ hostname }} {{ item }} --overwrite
  args:
    executable: /bin/bash
  delegate_to: k3smaster01
  when: labels is defined
  loop: "{{ labels }}"
