apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- resources/namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- resources/kustomize-with-helm.yaml
- resources/cert.yaml
- resources/ingress.yaml

patches:
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
    path: patches/patch.yaml
  - path: kustomize-with-helm-sidecar.yaml

