- name: Get domain
  environment:
    AWS_ACCESS_KEY_ID: "{{ ANSIBLE_AWS_ACCESS_KEY }}"
    AWS_SECRET_ACCESS_KEY: "{{ ANSIBLE_AWS_SECRET_KEY }}"
    AWS_DEFAULT_REGION: "eu-central-1"
  set_fact:
    external_domain: "{{ lookup('amazon.aws.aws_ssm', '/self_hosted/external_domain_name') }}"

- name: Download Helm command line tool
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    return_content: true
  register: helm_installer

- name: Install Helm
  ansible.builtin.command:
    cmd: bash
    stdin: "{{ helm_installer.content }}"
    creates: /usr/local/bin/helm
  environment:
    DESIRED_VERSION: "{{ helm_version | default('') }}"

- name: Install metrics-server
  ansible.builtin.shell: kubectl apply -k roles/apps/kustomization/metrics_server
  args:
    executable: /bin/bash

- name: Install purelb
  ansible.builtin.shell: kubectl apply -k roles/apps/kustomization/purelb
  args:
    executable: /bin/bash

- name: Install reflector
  ansible.builtin.shell: kubectl apply -k roles/apps/kustomization/reflector
  args:
    executable: /bin/bash

- name: Install cert-manager
  ansible.builtin.shell: kubectl apply -k roles/apps/kustomization/cert_manager
  args:
    executable: /bin/bash
#- name: Install metrics-server
#  k8s:
#    definition: "{{ lookup('kubernetes.core.kustomize', dir='roles/apps/kustomization/metrics_server') }}"#

#- name: Install purelb
#  k8s:
#    definition: "{{ lookup('kubernetes.core.kustomize', dir='roles/apps/kustomization/purelb') }}"#

#- name: Install reflector
#  k8s:
#    definition: "{{ lookup('kubernetes.core.kustomize', dir='roles/apps/kustomization/reflector') }}"#

#- name: Install cert manager
#  k8s:
#    definition: "{{ lookup('kubernetes.core.kustomize', dir='roles/apps/kustomization/cert_manager') }}"#

- name: Set up ingress resource
  local_action:
    module: ansible.builtin.template
    src: "templates/argocd_{{ item.resource_name }}.yaml.j2"
    dest: "ansible/roles/apps/argocd/resources/{{ item.resource_name }}.yaml"
  loop:
   - { resource_name: ingress }
   - { resource_name: cert }

- name: Install argocd
  ansible.builtin.shell: kubectl apply -k roles/apps/kustomization/argocd
  args:
    executable: /bin/bash
#- name: Install argocd
#  k8s:
#    definition: "{{ lookup('kubernetes.core.kustomize', dir='roles/apps/kustomization/argocd') }}"
