- name: Get domain
  environment:
    AWS_ACCESS_KEY_ID: "{{ ANSIBLE_AWS_ACCESS_KEY }}"
    AWS_SECRET_ACCESS_KEY: "{{ ANSIBLE_AWS_SECRET_KEY }}"
    AWS_DEFAULT_REGION: "eu-central-1"
  set_fact:
    external_domain: "{{ lookup('amazon.aws.aws_ssm', '/self_hosted/external_domain_name') }}"

- name: Download Helm command line tool
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    return_content: true
  register: helm_installer

- name: Install Helm
  ansible.builtin.command:
    cmd: bash
    stdin: "{{ helm_installer.content }}"
    creates: /usr/local/bin/helm
  environment:
    DESIRED_VERSION: "{{ helm_version | default('') }}"

- name: Install purelb
  k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir='roles/master/kustomization/purelb') }}"

- name: Install metrics-server
  k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir='roles/master/kustomization/metrics_server') }}"

- name: Install reflector
  k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir='roles/master/kustomization/reflector') }}"

- name: Install cert manager
  k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir='roles/master/kustomization/cert_manager') }}"

#- name: Install argocd
#  k8s:
#    definition: "{{ lookup('kubernetes.core.kustomize', dir='roles/master/kustomization/argocd') }}"
