- name: apply common configuration to all nodes
  hosts: all
  remote_user: ansible_user
  roles:
    - common

- name: configure and deploy k3s master nodes
  hosts: k3smasters
  remote_user: ansible_user
  roles:
    - master

- name: configure and deploy k3s agents
  hosts: k3sagents
  remote_user: ansible_user
  roles:
    - agent

- name: install k3s apps
  hosts: k3smasters
  remote_user: ansible_user
  roles:
    - apps