apiVersion: v1
kind: Service
metadata:
  name: argocd-http
  namespace: argocd
spec:
  selector:
    app: argocd-server
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  LoadBalancerIp: 192.168.0.150


