name: Run Ansible Playbook

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Wireguard set up
      uses: ./.github/actions/wireguard_setup
      with:
        endpoint: ${{ secrets.WG_ENDPOINT }}
        public_key: ${{ secrets.WG_PUBKEY }}
        private_key: ${{ secrets.WG_PRIVATE_KEY }}
        preshared_key: ${{ secrets.WG_PRESHARED_KEY }} 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-central-1
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github_actions_ansible_role
        role-session-name: awss
    - name: Run Ansible Playbook
      env:
        K3S_TOKEN: ${{ secrets.K3S_TOKEN }}
        ANSIBLE_HOST_KEY_CHECKING: "False"
      run: |
        sudo apt update
        sudo apt install -y ansible
        source /opt/pipx/venvs/ansible-core/bin/activate
        python -m pip install boto3 botocore
        deactivate
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        cd ansible
        echo "${{ secrets.ANSIBLE_USER_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        sed -i "s/\${ANSIBLE_AWS_ACCESS_KEY}/${{ secrets.ANSIBLE_AWS_ACCESS_KEY }}/g" group_vars/all
        sed -i "s/\${ANSIBLE_AWS_SECRET_KEY}/${{ secrets.ANSIBLE_AWS_SECRET_KEY }}/g" group_vars/all
        ansible-playbook -i inventory.yaml site.yaml --private-key=private_key.pem --user=${{ secrets.ANSIBLE_USER }}