name: packer run

on: 
  push:
    branches: 
      - 'dev1'

jobs:
  run:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up WireGuard
        run: chmod +x scripts/wg_setup.sh && scripts/wg_setup.sh
        shell: bash
        env:
          ARG_ENDPOINT: ${{ secrets.WG_ENDPOINT }}
          ARG_ENDPOINT_PUBLIC_KEY: ${{ secrets.WG_PUBKEY }}
          ARG_ASSIGNED_IPS: 192.168.0.5
          ARG_ALLOWED_IPS: 192.168.0.0/24
          ARG_PRIVATE_KEY: ${{ secrets.WG_PRIVATE_KEY }}
          ARG_PRESHARED_KEY: ${{ secrets.WG_PRESHARED_KEY }}
          ARG_KEEPALIVE: 25
      - name: Test connection
        run: |
          ping -c 4 192.168.0.2
          curl -k https://192.168.0.30:8006
      - name: Run deletion
        env:
          PROXMOX_URL: ${{ vars.PROXMOX_URL }}
          PROXMOX_USER: ${{ secrets.PROXMOX_API_USER }}
          PROXMOX_PASSWORD: ${{ secrets.PROXMOX_API_PASSWORD }}
        run: | 
          cd scripts
          pip install -r requirements.txt
          chmod +x pxmx_delete_vm.py && python pxmx_delete_vm.py -vm_id 102
