name: packer run

on: 
  push:
    branches: 
      - 'dev1'

jobs:
  run:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up WireGuard
        uses: egor-tensin/setup-wireguard@v1
        with:
          endpoint: '${{ secrets.WG_ENDPOINT }}'
          endpoint_public_key: '${{ secrets.WG_PUBKEY }}'
          ips: '${{ secrets.IPS }}'
          allowed_ips: '192.168.0.0/24'
          private_key: '${{ secrets.WG_PRIVATE_KEY }}'
          preshared_key: '${{ secrets.WG_PRESHARED_KEY }}'
      - name: Test connection
        run: |
          ping -c 4 192.168.0.2
          curl -k https://192.168.0.30:8006
      - name: Run deletion
        env:
          PROXMOX_URL: ${{ vars.PROXMOX_URL }}
          PROXMOX_USER: ${{ secrets.PROXMOX_API_USER }}
          PROXMOX_PASSWORD: ${{ secrets.PROXMOX_API_PASSWORD }}
        run: | 

          cd scripts
          pip install -r requirements.txt
          chmod +x pxmx_delete_vm.py && python pxmx_delete_vm.py -vm_id 102
