name: packer run

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install wireguard
      - run: echo "next"
      - run: echo "{{ secrets.WG_PRIVATE_KEY }}" > privatekey
      - run: echo "next"
      - run: sudo ip link add dev wg0 type wireguard
      - run: echo "next"
      - run: sudo ip address add dev wg0 192.168.0.5 peer 192.168.0.2
      - run: echo "next"
      - run: sudo wg set wg0 listen-port 48123 private-key privatekey peer {{ secrets.WG_PUBKEY }} allowed-ips {{ secrets.WG_ALLOWED_IPS }} endpoint {{ vars.WG_ENDPOINT }}
      - run: echo "next"
      - run: sudo ip link set up dev wg0
      - env:
          PROXMOX_URL: ${{ vars.PROXMOX_URL }}
          PROXMOX_USER: ${{ secrets.PROXMOX_API_USER }}
          PROXMOX_PASSWORD: ${{ secrets.PROXMOX_API_PASSWORD }}
        run: | 
          cd scripts
          pip install -r requirements.txt
          chown +x pmx_delete_vm.py && pmx_delete_vm.py -vm_id 102
