name: packer run

on: 
  push:
    branches: 
      - 'dev1'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: | 
          sudo apt install wireguard
          sudo echo "${{ secrets.WG_CONFIG }}" > ./wg0.conf
          sudo chmod 600 ./wg0.conf
          sudo wg-quick up ./wg0.conf
          sudo wg show
          sudo ip a
          echo "PAUSE 30s"
          sleep 
          curl -k https://192.168.0.30:8006
      - env:
          PROXMOX_URL: ${{ vars.PROXMOX_URL }}
          PROXMOX_USER: ${{ secrets.PROXMOX_API_USER }}
          PROXMOX_PASSWORD: ${{ secrets.PROXMOX_API_PASSWORD }}
        run: | 
          ls -la
          cd scripts
          pip install -r requirements.txt
          chmod +x pxmx_delete_vm.py && python pxmx_delete_vm.py -vm_id 102
