name: packer run

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: | 
          sudo apt install wireguard
          echo "${{ secrets.WG_CONFIG }}" > config.conf
          chmod 600 ./config.conf
          sudo wg-quick up ./config.conf
          sudo wg
          sudo ip a
          echo "PAUSE 30s"
          pause 30
      - env:
          PROXMOX_URL: ${{ vars.PROXMOX_URL }}
          PROXMOX_USER: ${{ secrets.PROXMOX_API_USER }}
          PROXMOX_PASSWORD: ${{ secrets.PROXMOX_API_PASSWORD }}
        run: | 
          ls -la
          cd scripts
          pip install -r requirements.txt
          chmod +x pxmx_delete_vm.py && python pxmx_delete_vm.py -vm_id 102
