name: Create VM template

on:
  workflow_dispatch:
    inputs:
      pipeline_path:
        description: 'VM pipeline (see in packer directory)'
        required: true
        type: choice
        options:
          - basic-debian-12.1.0-amd64-netinst
          - k3s-debian-12.1.0-amd64-netinst

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/wireguard_setup
        with:
          endpoint: ${{ secrets.WG_ENDPOINT }}
          public_key: ${{ secrets.WG_PUBKEY }}
          private_key: ${{ secrets.WG_PRIVATE_KEY }}
          preshared_key: ${{ secrets.WG_PRESHARED_KEY }}
      - name: Packer run
        env:
          PROXMOX_URL: ${{ vars.PROXMOX_URL }}
          PROXMOX_USER: ${{ secrets.PROXMOX_API_USER }}
          PROXMOX_PASSWORD: ${{ secrets.PROXMOX_API_PASSWORD }}
        run: |
          if [[ "${{ inputs.pipeline_path }}" == "k3s"* ]]; then
            VM_ID=103
            echo "k3s template. vm_id=103"
          fi
          if [[ "${{ inputs.pipeline_path }}" == "basic"* ]]; then
            VM_ID=102
            echo "basic template. vm_id=102"
          fi
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo sudo apt-get install packer
          cd scripts
          pip install -r requirements.txt
          echo "VM_ID = $VM_ID"
          chmod +x pxmx_delete_vm.py && python pxmx_delete_vm.py -vm_id $VM_ID
          cd ../packer/${{ inputs.pipeline_path }}
          sed -i "s/\${proxmox_api_user}/$PROXMOX_USER/g" variables.auto.pkrvars.hcl
          sed -i "s/\${proxmox_api_password}/$PROXMOX_PASSWORD/g" variables.auto.pkrvars.hcl
          sed -i "s/\${ansible_user_public_key}/${{ secrets.ANSIBLE_USER_PUBLIC_KEY }}/g" preseed.cfg
          packer init ./debian.pkr.hcl
          packer build .
