name: Pulumi Up

on:
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: ./.github/actions/wireguard_setup
        with:
          endpoint: ${{ secrets.WG_ENDPOINT }}
          public_key: ${{ secrets.WG_PUBKEY }}
          private_key: ${{ secrets.WG_PRIVATE_KEY }}
          preshared_key: ${{ secrets.WG_PRESHARED_KEY }}
      - run: | 
          cd pulumi_stack
          pip install -r requirements.txt
      - uses: pulumi/actions@v3
        with:
          work-dir: pulumi_stack
          command: up
          stack-name: 4ownops/proxmox
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PROXMOX_URL: ${{ vars.PROXMOX_URL }}
          PROXMOX_USER: ${{ secrets.PROXMOX_API_USER }}
          PROXMOX_PASSWORD: ${{ secrets.PROXMOX_API_PASSWORD }}

      